### PR TITLE
Feature/file field

### LINKED ISSUE #108: Feature request: 'FileField' class
I'd like to have a field to upload any file from my local filesystem and have it's value as a buffer.
Some nice validators I can think of: allow a set of suffixes, size limit ...

### PR DESCRIPTION
**Pull request by rilpires**
Resolves #108 
I haven't made the `CodeLink`-style example yet, I'll be pushing it soon

### CODE REVIEW

**Comment by Alvarocda** [comment]
I did some tests and it worked perfectly, I selected images, videos, and a PDF file and it worked perfectly. But I realized that the parameter "thumbnailSize" has no effect, well, at least not that I noticed, I used the example provided.

In addition, LGTM.

**Comment by Alvarocda** [comment]
The other test I did was on a tablet, but now I tested it on a regular smartphone (Pixel 3 XL Emulator) and I saw that the buttons and the interface have little space and end up being squeezed as shown in the image attached here.

I think it should be fixed before merging.

image

**Comment by rilpires** [comment]
To be clear: what is the expected behavior at this case?

**Comment by edufolly** [comment]
The buttons could have the same size.

**Comment by rilpires** [comment]
> (...) But I realized that the parameter "thumbnailSize" has no effect, well, at least not that I noticed, I used the example provided.
Thumbnail image isn't supposed to stretch in any axis. Changing from thumbnailSize: Size(64,64) to Size(1000,64) in a portrait(height>width) image won't have any effect. Should we force stretch-to-fill the thumbnailSize?

**Comment by rilpires** [comment]
> > (...) But I realized that the parameter "thumbnailSize" has no effect, well, at least not that I noticed, I used the example provided.
> 
> Thumbnail image isn't supposed to stretch in any axis. Changing from thumbnailSize: Size(64,64) to Size(1000,64) in a portrait(height>width) image won't have any effect. Should we force stretch-to-fill the thumbnailSize?

I saw a problem regarding thumbnailSize: it depends on space available from flex. In this example, I used thumbnailSize=(256,256), but width couldn't expand beyond what row offers

image

I fixed the gap that emerged from the height=256. What thumbnailSize specifies now is actually the max dimensions a image can have. It will always respect it's original aspect ratio and the flex size it is assigned to.

> The buttons could have the same size.

Also, delete button and load button both have the same flex weight now

**Comment by Alvarocda** [comment]
The buttons are ok now.
Just one last question, in the mobile version the thumbnail doesn't appear even if "showImageThumbnail" is set to true, is there any limitation for not showing the thumbnail in the mobile version? In the web version the Thumbnail view is working perfectly.

image

**Comment by rilpires** [comment]
I have no idea why this happens. Are you using `fileType: FileType.image` on the mobile??

**Comment by Alvarocda** [comment]
> I have no idea why this happens. Are you using `fileType: FileType.image` on the mobile??


Yes, i am using FileType.image

```dart
FileField(
  showImageThumbnail: true,
  thumbnailSize: const Size(1024, 1024),
  fileType: FileType.image,
  onSaved: (Uint8List? fileBytes) => _image = fileBytes,
  validator: (Uint8List? fileBytes) {
    return fileBytes == null ? 'No file selected' : null;
  },
),
```

**Comment by rilpires** [comment]
> The buttons are ok now. Just one last question, in the mobile version the thumbnail doesn't appear even if "showImageThumbnail" is set to true, is there any limitation for not showing the thumbnail in the mobile version? In the web version the Thumbnail view is working perfectly.
> 
> image

What about file system permissions? From this emulator, could it be that you forgot to set any relevant permission ([MANAGE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/manage-all-files#operations-allowed-manage-external-storage)) on a manifest-like file?

**Comment by rilpires** [comment]
Done! Thank you for the experiments

**Comment by Alvarocda** [comment]
> Well, I got it wrong yesterday and thought that all the problem was caused by "files[0]" instead "files.first". I will make tests on android properly from now on

haha, its ok.
onSaved and onChanged don't work on android and the cause is in the 2 open reviews in my previous comment, when you select a file using the WEB version, the files.first.bytes properties have data, but in the mobile version, this property is null and because of that, onSaved and onChanged never run in the mobile version.

If you need any help implementing this on Android, you can contact me on Discord.

**Comment by rilpires** [comment]
image
Done, android by default wasn't reading file content after loading. I've also inserted a parameter to use horizontal or vertical layout (which now is default since mobile is tight)

**Comment by Alvarocda** [comment]
Very good, I tested it now and it's working Thumbnail, onChanged and onSaved are working on Android and WEB version.
It can be merged now.
LGTM

**Review by Alvarocda — APPROVED** [review]

**Comment by edufolly** [comment]
LGTM.

**Pull request merged**
